author: Galvanize Inc. <foss@galvanize.com>
license: MIT
token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJHYWx2YW5pemUiLCJpYXQiOjE2OTgzNjEyNjAsImp0aSI6IjYzY2Y1YzdiZGZkZTNjYTgwNWQ2YjBkNGJmYmVmMTZkIiwiZXhwIjoxNjk4MzY4NDYwLCJkYXRhIjp7ImlkIjo0NDcwMTMsImVtYWlsIjoiY2Fza2lubmVyN0BnbWFpbC5jb20ifX0.3mHIfW9fiFgp2o99P84qNokrDjHOg_f7mYhkPZFICVEYJM6D_75rzvFuQHzcYlnx_dvvbBwdqRdBaNU0mBbh0A
